# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import csci4220_hw4_pb2 as csci4220__hw4__pb2


class KadImplStub(object):
  """Kadmelia implementation for CSCI-4220
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FindNode = channel.unary_unary(
        '/KadImpl/FindNode',
        request_serializer=csci4220__hw4__pb2.IDKey.SerializeToString,
        response_deserializer=csci4220__hw4__pb2.NodeList.FromString,
        )
    self.FindValue = channel.unary_unary(
        '/KadImpl/FindValue',
        request_serializer=csci4220__hw4__pb2.IDKey.SerializeToString,
        response_deserializer=csci4220__hw4__pb2.KV_Node_Wrapper.FromString,
        )
    self.Store = channel.unary_unary(
        '/KadImpl/Store',
        request_serializer=csci4220__hw4__pb2.KeyValue.SerializeToString,
        response_deserializer=csci4220__hw4__pb2.IDKey.FromString,
        )
    self.Quit = channel.unary_unary(
        '/KadImpl/Quit',
        request_serializer=csci4220__hw4__pb2.IDKey.SerializeToString,
        response_deserializer=csci4220__hw4__pb2.IDKey.FromString,
        )


class KadImplServicer(object):
  """Kadmelia implementation for CSCI-4220
  """

  def FindNode(self, request, context):
    """Takes an ID (use shared IDKey message type) and returns k nodes with
    distance closest to ID requested
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindValue(self, request, context):
    """Complicated - we might get a value back, or we might get k nodes with
    distance closest to key requested
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Store(self, request, context):
    """Store the value at the given node. Need to return *something*, but client
    does not use this return value.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Quit(self, request, context):
    """Notify a remote node that the node with ID in IDKey is quitting the
    network and should be removed from the remote node's k-buckets. Client
    does not use this return value.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KadImplServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FindNode': grpc.unary_unary_rpc_method_handler(
          servicer.FindNode,
          request_deserializer=csci4220__hw4__pb2.IDKey.FromString,
          response_serializer=csci4220__hw4__pb2.NodeList.SerializeToString,
      ),
      'FindValue': grpc.unary_unary_rpc_method_handler(
          servicer.FindValue,
          request_deserializer=csci4220__hw4__pb2.IDKey.FromString,
          response_serializer=csci4220__hw4__pb2.KV_Node_Wrapper.SerializeToString,
      ),
      'Store': grpc.unary_unary_rpc_method_handler(
          servicer.Store,
          request_deserializer=csci4220__hw4__pb2.KeyValue.FromString,
          response_serializer=csci4220__hw4__pb2.IDKey.SerializeToString,
      ),
      'Quit': grpc.unary_unary_rpc_method_handler(
          servicer.Quit,
          request_deserializer=csci4220__hw4__pb2.IDKey.FromString,
          response_serializer=csci4220__hw4__pb2.IDKey.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'KadImpl', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
